<?php include ('includes/header.php');
?>

<div class="container mt-4">
    <div class="row">
        <div class="">
            <img src="images/ganesha.png." class="img-fluid d-block mx-auto" alt="Image 6" height="400px">
            <div class="card-body">
                <h5 class="card-title text-center">Ganesha</h5>
                <p>
                Ganesh (also spelled Ganesa or Ganesha and known as Ganapati, Vinayaka and Pillaiyar) is the Lord of Good Fortune who provides prosperity, fortune and success. He is the Lord of Beginnings and the Remover of Obstacles of both material and spiritual kinds. Interestingly, he also places obstacles in the path of those who need to be checked.
                </p>
                <p>Because of these attributes, Ganesh is widely revered by almost all castes and in all parts of India, regardless of any other spiritual affiliations. His image is found everywhere, in many different forms, and he is invoked before the undertaking of any task. Ganesh is also associated with the first Chakra, or energy wheel, which underpins all of the other Chakras and represents conservation, survival and material well-being. He is considered to be a patron of the arts and sciences and of letters. Devotees believe that if Ganesha is worshiped, he grants success, prosperity and protection against adversity. In a lesser known role, Ganesh is also the destroyer of vanity, selfishness and pride.</p>
              
                <h5>Early Life</h5>
                <p>Ganesha is the son of Shiva and Parvati and he is the brother of Karthikeya (or Subrahmanya), the god of war. He was created by his mother using earth which she moulded into the shape of a boy. As Shiva was away on his meditative wanderings, Parvati set her new son as guard while she bathed. Unexpectedly, Shiva returned home and, on finding the boy, and outraged at his impudence in claiming he was Parvati's son, Shiva called for his gang of demons, the bhutaganas, who fought ferociously with the boy. However, the youngster easily held his own against such fearsome adversaries and Vishnu was forced to intervene in the form of Maya and, whilst the boy was distracted by her beauty, the demons, or Shiva himself, lopped off his head. At the commotion, Parvati ran from her bath and remonstrated with Shiva for so summarily killing their son. Repentant, Shiva ordered a new head to be found for the boy and, as the first animal available was an elephant, so Ganesha gained a new head and became the most distinctive of the Hindu gods. As a reward for his great courage in fighting the demons, Shiva made Ganesha the leader of the bhutaganas, hence his name.</p>
                <h5>Attributes & Characteristics</h5>
                <p>The attributes and characteristics of Ganesh have evolved over many centuries of Indian history. Several of the sacred Hindu texts relate myths and anecdotes associated with his birth and exploits and help to explain his distinct iconography. He is popularly held to be the son of Shiva and Parvati, although the Puranas(ancient Hindu and Jain texts narrating the history of the Universe and describing Hindu cosmology, philosophy and geography) disagree about his birth, stating that he may have been created by Shiva, or by Parvati, or by Shiva and Parvati, or may simply have been discovered by Shiva and Parvati. It is a little known fact outside of India that Ganesh has a brother Skanda, who is worshiped particularly in southern India as the embodiment of grace, bravery and love of virtuous deeds.</p>
                <p>Iconic representations of Ganesh show considerable variation, his form changing over time from that of a simple elephant in earliest depictions to the Ganesh we know today, typically having the head of an elephant and a large rotund belly. He is generally shown with four arms, although the number may vary from two to sixteen. When in the four-armed configuration he usually holds his own broken tusk in his lower-right hand and a laddoo sweet in his lower-left hand which he tastes with his trunk. </p>
                <p>Ganesh may be portrayed as standing, seated, in tantric yoga pose, dancing, crawling as a child (with his favourite laddoo sweet in one hand), or even seated on his mother's knee. When seated, he may be crossed legged or with one leg tucked under him in the position known as "royal ease". His mount or vehicle is usually the humble mouse, often shown at his feet looking adoringly up at him and offering a laddoo sweet in his paws. The combination of elephant and mouse represents the removal of all obstacles of any size and the ability of Ganesh to control even the most unpredictable of creatures and situations.</p>
              <h5>Stories & Legends</h5>
              <p>Some of the stories surrounding Ganesh are conflicting in nature, for example how his tusk came to be broken. One popular story is that he broke it off himself in order to write down the Mahabharata, one of the world's longest epic poems, as it was dictated to him by the sage Vyasa. In the process of writing, Ganesh's pen failed and so he snapped off his tusk as a replacement in order that the transcription not be interrupted. The broken tusk therefore symbolises sacrifice (particularly in the pursuit of artistic endeavours) and reiterates Ganesh's role as patron of the arts and of letters. However, another version of the broken-tusk story emphasises Ganesh's loyalty and devotion. In this account, his father Shiva decided to take a nap and asked Ganesh to guard him. A proud Brahmin warrior named Parashuram came to visit Shiva but was stopped from waking him by Ganesh. Parashuram was furious and fought with him, finally throwing his ax at his head. Ganesh stopped the ax with his tusk which broke, giving him the nickname Eka-danta, or "One Toothed."
Another common icon associated with Ganesh is that of the snake. According to one Purana, Ganesha simply wrapped the serpent king Vasuki around his neck. Ganesh may also be portrayed using the snake as a sacred thread, aloft in both hands, coiled at his ankles or as a throne. However the best known story of all concerns Ganesh wrapping the snake around his stomach as a belt. According to the legend, on one of his birthdays, Ganesh went from house to house accepting offerings of sweet puddings (in one version of the story the offerings are cakes made by a baker, who wishes to thank Ganesh for his good fortune in business). Out on the road his mount the mouse stumbles, having seen a snake and become frightened, with the result that Ganesh tumbles off. His stomach bursts open and all the sweet puddings fall out. Unwilling to leave them on the ground for all to see (or in the second version, for the baker to see on his way home from the bakery), Ganesh stuffs them back into his stomach and, catching hold of the snake, ties it around his belly. In some versions, the story simply stops there. But in others, the moon in the sky, on seeing this, has a hearty laugh at his expense. Annoyed, Ganesh pulls off one of his tusks and hurls it at the moon. Once again, the symbology behind the mouse, snake, Ganesh's belly and its relationship to the moon on his birthday is highly significant, his belly representing as it does the entire cosmos which is held together by the cosmic energy of the snake kundalini.
</p>
<h5>Ganesha’s Adventures</h5>
<p>A story which explains the god’s association with intelligence and wisdom is his competition with Karthikeya to be the first to marry. They set up a challenge that whoever could first encircle the Earth would also find a bride first. Not wasting a second, Karthikeya swiftly mounted his blue peacock and immediately shot off around the world. Ganesha on the other hand, casually sauntered over to his parents’ house, embraced them and quoted the line from the sacred Vedas: “he who embraces his parents seven times (pradakshinas) gains the merit of encircling the world seven times”. Declared the winner, Ganesha promptly married not one but two daughters of Prajapati: Buddhi (Wisdom) and Siddhi (Success), with whom he had two sons: Kshema and Laabha.</p>
<p>Ganesha also has something of a reputation for greediness. One day, after eating a few too many modakas (sacrificial cakes), Ganesha decided to take a ride on his giant rat, Kroncha, to aid his digestion. However, the rat was surprised when he came across a large snake and, jumping back with fear, he threw off his mount. Ganesha landed on his full belly and it burst on hitting the ground. The cakes from his stomach rolled left, right and centre but Ganesha, unperturbed, carefully gathered them in, stuffed them all back into his belly and wound the snake around his midriff to keep it closed. Symbolic of Ganesha’s ability to overcome all obstacles, the snake, the cause of the accident in the first place, therefore provided the remedy for the damage it had caused.
Continuing on his night-ride, Ganesha suddenly heard a thunderous noise from the heavens. This was the laughing of the Moon and his wives, the twenty seven Constellations, unable to contain themselves on seeing Ganesha wrapped in a snake. Outraged, Ganesha broke off the end of one of his tusks and hurled it at the laughing Moon who, hit full in the face, was struck black. Without the light of the moon, the dark nights became the haunt of thieves and villains until honest people had had enough and pleaded with the gods to restore the silver light. The gods asked Ganesha to forgive the Moon but only a partial forgiveness was given. Consequently, only periodically, on one night, would the Moon give his full light and then he would slowly waste away.
</p>

<p>An alternative explanation of Gane”ha's’broken tusk is that of Krishna throwing his axe at Ganesha after he blocked his entrance to the private apartments of his parents Shiva and Parvati. Ganesha allowed the axe to hit and break his tusk so that no-one could say that the axe, which was in fact his father’s, was not a fearsome weapon. Yet another but less picturesque explanation of Ganesha’s broken tusk was that he snapped it off in order to transcribe the epic poem Mahabharata, dictated by the sage Vyasa who wished to preserve the story for all time. This version explains Ganesha’s association with writers and intellectuals.</p>
            </div>

        </div>
        
        
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>
