<?php include ('includes/header.php');
?>
<div class="container mt-4">
    <div class="row">
        <div class="">
            <img src="images/mahabartha-1.jpg." class="img-fluid d-block mx-auto" alt="Image 6" height="400px">
            <div class="card-body">
                <h5 class="card-title text-center">Mahabharata</h5>
                <p>The Mahabharata is an ancient Indian epic where the main story revolves around two branches of a family - the Pandavas and Kauravas - who, in the Kurukshetra War, battle for the throne of Hastinapura. Interwoven into this narrative are several smaller stories about people dead or living, and philosophical discourses. Krishna- Dwaipayan Vyasa, himself a character in the epic, composed it; as, according to tradition, he dictated the verses and Ganesha wrote them down. At 100,000 verses, it is the longest epic poem ever written, generally thought to have been composed in the 4th century BCE or earlier. The events in the epic play out in the Indian subcontinent and surrounding areas. It was first narrated by a student of Vyasa at a snake-sacrifice of the great- grandson of one of the major characters of the story. Including within it the Bhagavad Gita, the Mahabharata is one of the most important texts of ancient Indian, indeed world, literature. (Source: www.ancient.eu)</p>
                <h5>The Prelude</h5>
              <p>Shantanu, the king of Hastinapur, was married to Ganga (personification of the Ganges) with whom he had a son called Devavrat. Several years later, when Devavrat had grown up to be an accomplished prince, Shantanu fell in love with Satyavati. Her father refused to let her marry the king unless the king promised that Satyavati's son and descendants would inherit the throne. Unwilling to deny Devavrat his rights, Shantanu declined to do so but the prince, on coming to know of the matter, rode over to Satyavati's house, vowed to renounce the throne and to remain celibate throughout his life. The prince then took Satyavati home to the palace so that the king, his father, could marry her. On account of the terrible vow that he'd taken that day, Devavrat came to be known as Bheeshm. Shantanu was so pleased with his son that he granted to Devavrat the boon of choosing the time of his own death.</p>
              <p>In time, Shantanu and Satyavati had two sons. Soon thereafter, Shantanu died. Satyavati's sons still being minors, the affairs of the kingdom were managed by Bheeshm and Satyavati. By the time these sons reached adulthood, the elder one had died in a skirmish with some gandharvas (heavenly beings) so the younger son, Vichitravirya, was enthroned. Bheeshm then abducted the three princesses of a neighbouring kingdom and brought them over to Hastinapur to be wedded to Vichitravirya. The eldest of these princesses declared that she was in love with someone else, so she was let go; the two other princesses were married to Vichitravirya who died soon afterwards, childless.</p>
              <h5>Dhritarashtra, Pandu & Vidur</h5>
              <p>So that the family line did not die out, Satyavati summoned her son Vyasa to impregnate the two queens. Vyasa had been born to Satyavati of a great sage named Parashar before her marriage to Shantanu. According to the laws of the day, a child born to an unwed mother was taken to be a step-child of the mother's husband; by that token, Vyasa could be considered Shantanu's son and could be used to perpetuate the Kuru clan that ruled Hastinapur. Thus, by the Niyog custom, the two queens each had a son of Vyasa: to the elder queen was born a blind son called Dhritarashtra, and to the younger was born an otherwise healthy but extremely pale son called Pandu. To a maid of these queens was born a son of Vyasa called Vidur. Bheeshm brought up these three boys with great care. Dhritarashtra grew up to be the strongest of all princes in the country, Pandu was extremely skilled in warfare and archery, and Vidur knew all the branches of learning, politics, and statesmanship.</p>
              <p>With the boys grown, it was now time to fill up the empty throne of Hastinapur. Dhritarashtra, the eldest, was bypassed because the laws barred a disabled person from being king. Pandu, instead, was crowned. Bheeshm negotiated Dhritarashtra's marriage with Gandhari, and Pandu's with Kunti and Madri. Pandu expanded the kingdom by conquering the sorrounding areas, and brought in considerable war booty. With things running smoothly in the country, and with its coffers full, Pandu asked his elder brother to look after the state affairs, and retired to the forests with his two wives for some time off.</p>
              <h5>Kauravas & Pandavas</h5>
              <p>A few years later, Kunti returned to Hastinapur. With her were five little boys, and the bodies of Pandu and Madri. The five boys were the sons of Pandu, born to his two wives through the Niyog custom from gods: the eldest was born of Dharma, the second of Vayu, the third of Indra, and the youngest - twins - of the Ashvins. In the meanwhile, Dhritarashtra and Gandhari too had had children of their own: 100 sons and one daughter. The Kuru elders performed the last rites for Pandu and Madri, and Kunti and the children were welcomed into the palace.</p>
              <p>All of the 105 princes were subsequently entrusted to the care of a teacher: Kripa at first and, additionally, Drona later. Drona's school at Hastinapur attracted several other boys; Karna, of the Suta clan was one such boy. It was here that hostilities quickly developed between the sons of Dhritarashtra (collectively called the Kauravas, patronymic of their ancestor Kuru) and the sons of Pandu (collectively called the Pandavas, patronymic of their father).</p>
              <p>Duryodhana, the eldest Kaurava, tried - and failed - to poison Bheem, the second Pandava. Karna, because of his rivalry in archery with the third Pandava, Arjuna, allied himself with Duryodhan. In time, the princes learnt all they could from their teachers, and the Kuru elders decided to hold a public skills exhibition of the princes. It was during this exhibition that the citizens became plainly aware of the hostilities between the two branches of the royal family: Duryodhan and Bheem had a mace fight that had to be stopped before things turned ugly, Karna - uninvited as he was not a Kuru prince - challenged Arjuna, was insulted on account of his non- royal birth, and was crowned king of a vassal state on the spot by Duryodhan. It was also around this time that questions began to be raised about Dhritarashtra occupying the throne, since he was supposed to be holding it only in trust for Pandu, the crowned king. To keep peace in the realm, Dhritarashtra declared the eldest Pandava, Yudhishthir, as the crown prince and heir apparent.</p>
              <h5>The First Exile</h5>
              <p>Yudhishthir's being the crown prince and his rising popularity with the citizens was extremely distasteful to Duryodhan, who saw himself as the rightful heir since his father was the de facto king. He plotted to get rid of the Pandavas. This he did by getting his father to send the Pandavas and Kunti off to a nearby town on the pretext of a fair that was held there. The palace in which the Pandavas were to stay in that town was built by an agent of Duryodhan; the palace was made entirely of inflammable materials since the plan was to burn down the palace - together with the Pandavas and Kunti – once they'd settled in. The Pandavas, however, were alerted to this fact by their other uncle, Vidur, and had a counter plan ready; they dug an escape tunnel underneath their chambers. One night, the Pandavas gave out a huge feast which all of the townsfolk came to. At that feast, a forest woman and her five sons found themselves so well-fed and well-drunk that they could no longer walk straight; they passed out on the floor of the hall. That very night, the Pandavas themselves set fire to the palace and escaped through the tunnel. When the flames had died down, the townsfolk discovered the bones of the forest woman and her boys, and mistook them for Kunti and the Pandavas. Duryodhan thought his plan had succeeded and that the world was free of the Pandavas.</p>
           <h5>Arjuna & Draupadi</h5>
           <p>Meanwhile, the Pandavas and Kunti went into hiding, moving from one place to another and passing themselves off as a poor brahmin family. They would seek shelter with some villager for a few weeks, the princes would go out daily to beg for food, return in the evenings and hand over the day's earnings to Kunti who would divide the food into two: one half was for the strongman Bheem and the other half was shared by the others. During these wanderings, Bheem killed two demons, married a demoness, and had a demon child called Ghatotkach. They then heard about a swayamvar (a ceremony to choose a suitor) being organised for the princess of Panchal, and went at Panchal to see the festivities. According to their practice, they left their mother home and set out for alms: they reached the swayamvar hall where the king was giving away things most lavishly to alms seekers. The brothers sat themselves down in the hall to watch the fun: the princess Draupadi, born of fire, was famed for her beauty and every prince from every country for miles around had come to the swayamvar, hoping to win her hand. The conditions of the swayamvar were difficult: a long pole on the ground had a circular contraption spinning at its top. On this moving disc was attached a fish. At the bottom of the pole was a shallow urn of water. A person had to look down into this water-mirror, use the bow and five arrows that were provided, and pierce the fish spinning on top. Five attempts were allowed. It was evident that only an extremely skilled archer, such as the now-presumed-dead Arjuna, could pass the test.</p>
           <p>One by one, the kings and princes tried to shoot the fish, and failed. Some could not even lift the bow; some could not string it. The Kauravas and Karna were also present. Karna picked up the bow and strung it in a moment, but was prevented from taking aim when Draupadi declared she would not marry anyone from the Suta clan. After every one of the royals had failed, Arjuna, the third Pandava, stepped up to the pole, picked up the bow, strung it, affixed all of the five arrows to it, looked down into the water, aimed, shot, and pierced the fish's eye with all of the five arrows in a single attempt. Arjuna had won Draupadi's hand.
The Pandava brothers, still in the guise of poor brahmins, took Draupadi back to the hut they were staying at and shouted for Kunti, "Ma, Ma, come and see what we've brought back today." Kunti, saying, "Whatever it is, share it among yourselves", came out of the hut, saw that it wasn't alms but the most beautiful woman she had ever set her eyes on, and stood stock still as the import of her words sank in on everybody present.

Meanwhile, Draupadi's twin Dhrishtadyumna, unhappy that his royal sister should be married off to a poor commoner, had secretly followed the Pandavas back to their hut. Also following them secretly was a dark prince and his fair brother - Krishna and Balaram of the Yadava clan - who had suspected that the unknown archer could be none other than Arjuna, who had been presumed dead at the palace-burning incident several months ago. These princes were related to the Pandavas - their father was Kunti's brother - but they had never met before. By design or happenstance, Vyasa also arrived at the scene at this point and the Pandava hut was alive for a while with happy cries of meetings and reunions. To keep Kunti's words, it was decided that Draupadi would be the common wife of all of the five Pandavas. Her brother, Dhrishtadyumna, and her father, the king Drupad, were reluctant with this unusual arrangement but were talked around to it by Vyasa and Yudhishthir.
</p>
<h5>Indraprastha & The Dice Game</h5>
<p>[11:57 pm, 29/4/2024] 😊: After the wedding ceremonies at Panchal were over, the Hastinapur palace invited the Pandavas and their bride back. Dhritarashtra made a great show of happiness on discovering that the Pandavas were alive after all, and he partitioned the kingdom, giving them a huge tract of barren land to settle in and rule over. The Pandavas transformed this land into a paradise. Yudhishthir was crowned there, and he performed a sacrifice that involved all of the kings of the land to accept - either voluntarily or by force - his suzerainty. The new kingdom, Indraprastha, prospered.</p>
<p>Meanwhile, the Pandavas had entered into an agreement among themselves regarding Draupadi: she was to be wife of each Pandava, by turn, for a year. If any Pandava was to enter the room where she was present with her husband-of-that-year, that Pandava was to be exiled for 12 years. It so happened that once Draupadi and Yudhishthir, her husband of that year, were present in the armoury when Arjuna entered it to take his bow and arrows. Consequently, he went off in exile during which he toured the entire country, down to its southernmost tip, and married three princesses he met along the way.</p>
<p>The prosperity of Indraprastha and the power of the Pandavas was not something that Duryodhan liked. He invited Yudhisthir to a dice game and got his uncle, Shakuni, to play on his (Duryodhan's) behalf. Shakuni was an accomplished player; Yudhishthir staked - and lost - step by step his entire wealth, his kingdom, his brothers, himself, and Draupadi. Draupadi was dragged into the dice hall and insulted. There was an attempt to disrobe her, and Bheem lost his temper and vowed to kill each and every one of the Kauravas. Things came to such a boil that Dhritarashtra intervened unwillingly, gave the kingdom and their freedom back to the Pandavas and Draupadi, and set them off back to Indraprastha. This angered Duryodhan, who talked his father around, and invited Yudhishthir to another dice game. This time, the condition was that the loser would go on a 12-year exile followed by a year of life incognito. If they were to be discovered during this incognito period, the loser would have to repeat the 12+1 cycle. The dice game was played. Yudhishthir lost again</p>
<h5>The Second Exile</h5>
<p>Hastinapur, in Vidur's place. They lived in forests, hunted game, and visited holy spots. At around this time, Yudhishthir asked Arjuna to go to the heavens in quest of celestial weapons because, by now, it was apparent that their kingdom would not be returned to them peacefully after the exile and that they would have to fight for it. Arjuna did so, and not only did he learn the techniques of several divine weapons from the gods, he also learnt how to sing and dance from the gandharvas.

After 12 years, the Pandavas went incognito for a year. During this one-year period, they lived in the Virat kingdom. Yudhishthir took up employment as a king's counsellor, Bheem worked in the royal kitchens, Arjuna turned himself into a eunuch and taught the palace maidens how to sing and dance, the twins worked at the royal stables, and Draupadi became a handmaiden to the queen. At the end of the incognito period - during which they were not discovered despite Duryodhan's best efforts - the Pandavas revealed themselves. The Virat king was overwhelmed; he offered his daughter in marriage to Arjuna but he declined since he had been her dance teacher the past year and students were akin to children. The princess was married, instead, to Arjuna's son Abhimanyu.
</p>
<p>Hastinapur, in Vidur's place. They lived in forests, hunted game, and visited holy spots. At around this time, Yudhishthir asked Arjuna to go to the heavens in quest of celestial weapons because, by now, it was apparent that their kingdom would not be returned to them peacefully after the exile and that they would have to fight for it. Arjuna did so, and not only did he learn the techniques of several divine weapons from the gods, he also learnt how to sing and dance from the gandharvas.

After 12 years, the Pandavas went incognito for a year. During this one-year period, they lived in the Virat kingdom. Yudhishthir took up employment as a king's counsellor, Bheem worked in the royal kitchens, Arjuna turned himself into a eunuch and taught the palace maidens how to sing and dance, the twins worked at the royal stables, and Draupadi became a handmaiden to the queen. At the end of the incognito period - during which they were not discovered despite Duryodhan's best efforts - the Pandavas revealed themselves. The Virat king was overwhelmed; he offered his daughter in marriage to Arjuna but he declined since he had been her dance teacher the past year and students were akin to children. The princess was married, instead, to Arjuna's son Abhimanyu.
</p>
<h5>The Kurukshetra War & Aftermath

</h5>
<p>Just before the war bugle was sounded, Arjuna saw arrayed before him his relatives: his great-grandfather Bheeshm who had practically brought him up, his teachers Kripa and Drona, his brothers the Kauravas, and, for a moment, his resolution wavered. Krishna, the warrior par excellence, had given up arms for this war and had elected to be Arjuna's charioteer. To him Arjuna said, "Take me back, Krishna. I can't kill these people. They're my father, my brothers, my teachers, my uncles, my sons. What good is a kingdom that's gained at the cost of their lives?" Then followed a philosophical discourse that has today become a separate book on its own - the Bhagavad Gita. Krishna explained the impermanence of life to Arjuna, and the importance of doing one's duty and of sticking to the right path. Arjuna picked up his bow again.</p>
<p>Panadava side and 11 on the Kaurava (1 akshauhini = 21,870 chariots + 21,870 elephants + 65,610 horses + 109,350 soldiers on foot). Casualties on both sides were high. When it all ended, the Pandavas had won the war but lost almost everyone they held dear. Duryodhan and all of the Kauravas had died, as had all of the menfolk of Draupadi's family, including all of her sons by the Pandavas. The now-dead Karna was revealed to be a son of Kunti's from before her marriage to Pandu, and thus, the eldest Pandava and the rightful heir to the throne. The grand old man, Bheeshm, lay dying; their teacher Drona was dead as were several kinsfolk related to them either by blood or by marriage. In about 18 days, the entire country lost almost three generations of its men. It was a war not seen on a scale before, it was the Great Indian war, the Maha-bharat.</p>
<p>After the war, Yudhishthir became king of Hastinapur and Indraprastha. The Pandavas ruled for 36 years, after which they abdicated in favour of Abhimanyu's son, Parikshit. The Pandavas and Draupadi proceeded on foot to the Himalayas, intending to live out their last days climbing the slopes heavenwards. One by one, they fell on this last journey and their spirits ascended to the heavens. Years later, Parikshit's son succeeded his father as king. He held a big sacrifice, at which this entire story was recited for the first time by a disciple of Vyasa called Vaishampayan.</p>
<h5>Legacy</h5>
<p>Since that time, this story has been retold countless times, expanded upon, and retold again. The Mahabharata remains popular to this day in India. It has been adapted and recast in contemporary mode in several films and plays. Children continue to be named after the characters in the epic. The Bhagvad Gita is one of the holiest of Hindu scriptures. Beyond India, the Mahabharata story is popular in south-east Asia in cultures that were influenced by Hinduism such as Indonesia and Malaysia.</p>
            </div>

        </div>
        
        
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>
