<?php include ('includes/header.php');
?>

<div class="container mt-4">
    <div class="row">
        <div class="">
            <img src="images/ramayana-1.jpg." class="img-fluid d-block mx-auto" alt="Image 6" height="400px">
            <div class="card-body">
                <h5 class="card-title text-center">Ramayana</h5>
               <p>The Ramayana is an ancient Indian epic, composed some time in the 5th century BCE, about the exile and then return of Rama, prince of Ayodhya. It was composed in Sanskrit by the sage Valmiki, who taught it to Rama's sons, the twins Lava and Kush. At about 24000 verses, it is a rather long poem and, by tradition, is known as the Adi Kavya (adi = original, first; kavya = poem). While the basic story is about palace politics and battles with demon tribes, the narrative is interspersed with philosophy, ethics, and notes on duty. While in that other Indian epic, the Mahabharata, the characters are presented with all their human follies and failings, the Ramayana leans more towards an ideal state of things: Rama is the ideal son and king, Sita the ideal wife, Hanuman the ideal devotee, Lakshman and Bharat the ideal brothers, and even Ravana, the demon villian, is not entirely despicable.</p>
               <h5>Bala Kanda</h5>
               <p>Dasharatha was the king of Ayodhya. He had three wives: Kaushalya, Kaikeyi and Sumitra. He was childless or a long time and anxious to produce an heir, so he performs a fire sacrifice known as putra-kameshti yagya. As a consequence, Rama is first born to Kaushalya, Bharata is born to Kaikeyi, Lakshmana and Shatrughna are born to Sumitra. These sons are endowed, to various degrees, with the essence of the Supreme Trinity Entity Vishnu; Vishnu had opted to be born into mortality to combat the demon Ravana, who was oppressing the gods, and who could only be destroyed by a mortal. The boys are reared as the princes of the realm, receiving instructions from the scriptures and in warfare from Vashistha. When Rama is 16 years old, sage Vishwamitra comes to the court of Dasharatha in search of help against demons who were disturbing sacrificial rites. He chooses Rama, who is followed by Lakshmana, his constant companion throughout the story. Rama and Lakshmana receive instructions and supernatural weapons from Vishwamitra and proceed to destroy the demons. </p>
               <p>Janaka was the king of Mithila. One day, a female child was found in the field by the king in the deep furrow dug by his plough. Overwhelmed with joy, the king regarded the child as a "miraculous gift of god". The child was named Sita, the Sanskrit word for furrow. Sita grew up to be a girl of unparalleled beauty and charm. The king had decided that who ever could lift and wield the heavy bow, presented to his ancestors by Shiva, could marry Sita. Sage Vishwamitra takes Rama and Lakshmana to Mithila to show the bow. Then Rama desires to lift it and goes on to wield the bow and when he draws the string, it breaks. Marriages are arranged between the sons of Dasharatha and daughters of Janaka. Rama gets married to Sita, Lakshmana to Urmila, Bharata to Mandavi and Shatrughna to Shrutakirti. The weddings are celebrated with great festivity in Mithila and the marriage party returns to Ayodhya.</p>
               <h5>Ayodhya Kanda</h5>
               <p>After Rama and Sita have been married for twelve years, an elderly Dasharatha expresses his desire to crown Rama, to which the Kosala assembly and his subjects express their support. On the eve of the great event, Kaikeyi - her jealousy aroused by Manthara, a wicked maidservant - claims two boons that Dasharatha had long ago granted her. Kaikeyi demands Rama to be exiled into the wilderness for fourteen years, while the succession passes to her son Bharata. The heartbroken king, constrained by his rigid devotion to his given word, accedes to Kaikeyi's demands. Rama accepts his father's reluctant decree with absolute submission and calm self-control which characterises him throughout the story. He is joined by Sita and Lakshmana. When he asks Sita not to follow him, she says, "the forest where you dwell is Ayodhya for me and Ayodhya without you is a veritable hell for me." After Rama's departure, King Dasharatha, unable to bear the grief, passes away. Meanwhile, Bharata who was on a visit to his maternal uncle, learns about the events in Ayodhya. Bharata refuses to profit from his mother's wicked scheming and visits Rama in the forest. He requests Rama to return and rule. But Rama, determined to carry out his father's orders to the letter, refuses to return before the period of exile. However, Bharata carries Rama's sandals and keeps them on the throne, while he rules as Rama's regent.</p>
               <h5>Aranya Kanda</h5>
               <p>Thirteen years pass and in the last year of exile Rama, Sita and Lakshmana journey southward along the banks of river Godavari, where they build cottages and live off the land. At the Panchavati forest they are visited by a rakshasa (demon) woman, Surpanakha, sister of Ravana. She attempts to seduce the brothers and failing in this, attempts to kill Sita. Lakshmana stops her by cutting off her nose and ears. Hearing of this, her demon brother, Khara, organises an attack against the princes. Rama annihilates Khara and his demons.</p>
               <p>When news of these events reaches Ravana, he resolves to destroy Rama by capturing Sita with the aid of the rakshasa Maricha. Maricha, assuming the form of a golden deer, captivates Sita's attention. Entranced by the beauty of the deer, Sita pleads with Rama to capture it. Lord Rama, aware that this is the ploy of the demons, cannot dissuade Sita from her desire and chases the deer into the forest, leaving Sita under Lakshmana's guard. After some time, Sita hears Rama calling out to her; afraid for his life, she insists that Lakshmana rush to his aid. Lakshmana tries to assure her that Rama is invincible and that it is best if he continues to follow Rama's orders to protect her. On the verge of hysterics, Sita insists that it is not she but Rama who needs Lakshmana's help. He obeys her wish but stipulates that she is not to leave the cottage or entertain any strangers. He draws a chalk outline, the Lakshmana rekha, around the cottage and casts a spell on it that prevents anyone from entering the boundary but allows people to exit. With the coast finally clear, Ravana appears in the guise of an ascetic requesting Sita's hospitality. Unaware of the devious plan of her guest, Sita is tricked into leaving the rekha and is then forcibly carried away by the evil Ravana.</p>
               <p>Jatayu, a vulture, tries to rescue Sita, but is mortally wounded. At Lanka, Sita is kept under the heavy guard of rakshasis. Ravana demands Sita marry him, but Sita, eternally devoted to Rama, refuses. Rama and Lakshmana learn about Sita's abduction from Jatayu and immediately set out to save her. During their search, they meet the demon Kabandha and the ascetic Shabari, who direct them towards Sugriva and Hanuman.</p>
               <h5>Kishkindha Kanda</h5>
               <p>Kishkindha Kanda is set in the ape (Vanara) citadel Kishkindha. Rama and Lakshmana meet Hanuman, the biggest devotee of Rama, greatest of ape heroes and an adherent of Sugriva, the banished pretender to the throne of Kishkindha. Rama befriends Sugriva and helps him by killing his elder brother Vali thus regaining the kingdom of Kishkindha, in exchange for helping Rama to recover Sita. However Sugriva soon forgets his promise and spends his time in enjoying his powers. The clever former ape queen Tara (wife of Vali) calmly intervenes to prevent an enraged Lakshmana from destroying the ape citadel. She then eloquently convinces Sugriva to honour his pledge. Sugriva then sends search parties to the four corners of the earth, only to return without success from north, east and west. The southern search party under the leadership of Angada and Hanuman learns from a vulture named Sampati (elder brother of Jatayu), that Sita was taken to Lanka.</p>
               <h5>Sundara Kanda</h5>
               <p>Sundara Kanda forms the heart of Valmiki's Ramayana and consists of a detailed, vivid account of Hanuman's adventures. After learning about Sita, Hanuman assumes a gargantuan form and makes a colossal leap across the sea to Lanka. On the way he meets with many challenges like facing a Gandharva kanya who comes in the form of a demon to test his abilities. He encounters a mountain named Mainakudu who offers Lord Hanuman assistance and offers him rest. Lord Hanuman refuses because there is little time remaining to complete the search for Sita.</p>
               <p>After entering into Lanka, he finds a demon, Lankini, who protects all of Lanka. Hanuman fights with her and subjugates her in order to get into Lanka. In the process Lankini, who had a earlier vision/warning from the gods that the end of Lanka nears if someone defeats Lankini. Here, Hanuman explores the demons' kingdom and spies on Ravana. He locates Sita in Ashoka grove, where she is being wooed and threatened by Ravana and his rakshasis to marry Ravana. Hanuman reassures Sita, giving Rama's signet ring as a sign of good faith. He offers to carry Sita back to Rama; however, she refuses and says that it is not the dharma, stating that Ramayana will not have significance if Hanuman carries her to Rama - "When Rama is not there Ravana carried Sita forcibly and when Ravana was not there, Hanuman carried Sita back to Rama". She says that Rama himself must come and avenge the insult of her abduction. Hanuman then wreaks havoc in Lanka by destroying trees and buildings and killing Ravana's warriors. He allows himself to be captured and delivered to Ravana. He gives a bold lecture to Ravana to release Sita. He is condemned and his tail is set on fire, but he escapes his bonds and leaping from roof to roof, sets fire to Ravana's citadel and makes the giant leap back from the island. The joyous search party returns to Kishkindha with the news.</p>
               <h5>Yuddha Kanda</h5>
               <p>Also known as Lanka Kanda, this book describes the Ramayana War between the army of Rama and the army of Ravana. Having received Hanuman's report on Sita, Rama and Lakshmana proceed with their allies towards the shore of the southern sea. There they are joined by Ravana's renegade brother Vibhishana. The apes named Nala and Nila construct a floating bridge (known as Rama Setu) across the sea, using stones that floated on water because they had Rama's name written on them. The princes and their army cross over to Lanka. A lengthy war ensues. During a battle, Ravana's son Indrajit hurls a powerful weapon at Lakshmana, who is badly wounded and is nearly killed. So Hanuman assumes a gigantic form and flies from Lanka to the Himalayas. Upon reaching Mount Sumeru, Hanuman was unable to identify the herb that could cure Lakshmana and so decided to bring the entire mountain back to Lanka. Eventually, the war ends when Rama kills Ravana. Rama then installs Vibhishana on the throne of Lanka.</p>
               <p>On meeting Sita, Rama asks her to undergo an Agni Pariksha (test of fire) to prove her chastity, as he wants to get rid of the rumors surrounding her purity. When Sita plunges into the sacrificial fire, Agni, lord of fire raises Sita, unharmed, to the throne, attesting to her innocence. The episode of Agni Pariksha varies in the versions of Ramayana by Valmiki and Tulsidas. In earlier versions, this event does not occur and many scholars consider it to have been added later as society became more patriarchal [citation needed]. In Tulsidas's Ramacharitamanas, Sita was under the protection of Agni so it was necessary to bring her out before reuniting with Rama. At the expiration of his term of exile, Rama returns to Ayodhya with Sita and Lakshmana, where the coronation is performed. This is the beginning of Ram Rajya, which implies an ideal state with good morals.</p>
               <h5>Uttara Kanda</h5>
               <p>Uttara Kanda is regarded to be a later addition to the original story by Valmiki and concerns the final years of Rama, Sita and Rama's brothers. After being crowned king, Rama passes time pleasantly with Sita. After some time, Sita gets pregnant with twin children. However, despite Agni Pariksha ("fire ordeal") of Sita, rumours about her "purity" are spreading among the populace of Ayodhya. Rama yields to public opinion and reluctantly banishes Sita to the forest, where the sage Valmiki provides shelter in his ashrama ("hermitage"). Here, she gives birth to twin boys, Lava and Kusha, who become pupils of Valmiki and are brought up in ignorance of their identity.</p>
               <p>Valmiki composes the Ramayana and teaches Lava and Kusha to sing it. Later, Rama holds a ceremony during the Ashwamedha yagna, which sage Valmiki, with Lava and Kusha, attends. Lava and Kusha sing the Ramayana in the presence of Rama and his vast audience. When Lava and Kusha recite about Sita's exile, Rama becomes grief-stricken and Valmiki produces Sita. Sita calls upon the Earth, her mother, to receive her and as the ground opens, she vanishes into it. Rama then learns that Lava and Kusha are his children. Many years later, a messenger from the Gods appears and informs Rama that the mission of his incarnation is over. Rama returns to his celestial abode along with his brothers. It was dramatised as Uttararamacarita by the Sanskrit poet Bhavabhuti.</p>
               <h5>Regional Variations & Legacy</h5>
               <p>The Ramayana was composed in Sanskrit. Over the years of re-tellings, several vernacular versions emerged that embellished the story, added regional touches, and inserted explanations and justifications for those bits that showed the hero, Rama, in a not-too-heroic light. The Ramavataram, composed by the Tamil poet Kamban in the 12th century CE, is popular in the southern parts of India. In the north, the Ramacharit Manas, composed by the Awadhi poet Tulsidas, is extremely popular. Other variations exist in Bengali, Malayalam, Telegu, Kannada, and other Indian languages.</p>
               <p>The Ramayana's characters have found their way into the common speech and idiom of the land. Public recitations of the Ramayana are common. The epic has been adapted into plays and films; it is also enacted every year by local troupes and neighbourhood societies in North India during the Dusshera festivities of the present times. Scenes from the epic can be seen on the walls of some of the oldest temples across Asia.

Rama is worshipped as an incarnation of god Vishnu, and it is not uncommon to find a Rama temple in almost every other neighbourhood in the country in the northern parts of India, especially in the Gangetic belt. In countries of South-East Asia, such as Cambodia, Indonesia, and Malaysia, the story of Rama continues to be told through intricately crafted shadow puppet shows.
</p>
            </div>

        </div>
        
        
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>
